use std::path::Path;

fn main() {
    // Capture the host target triple at compile time so the `cc` crate
    // can be driven at *runtime* (when building grammars). `cc` normally
    // reads TARGET/HOST from the build-script environment, which isn't
    // present in the running binary — so we stash it in an env var.
    let target = std::env::var("TARGET").expect("cargo sets TARGET for build scripts");
    println!("cargo:rustc-env=BUILD_TARGET={}", target);

    // When the `bundled-grammars` feature is on, generate a Rust source
    // file listing the pre-built, gzip-compressed grammar libraries for
    // this target so they can be `include_bytes!`'d into the binary.
    // The artifacts live under `assets/grammars-prebuilt/<target>/` and
    // are produced by `vorto grammar bundle` (run per-target in release
    // CI). When the feature is off we still emit an empty table so the
    // runtime module compiles either way.
    generate_bundled_grammars(&target);
}

fn generate_bundled_grammars(target: &str) {
    let out_dir = std::env::var("OUT_DIR").expect("cargo sets OUT_DIR");
    let dest = Path::new(&out_dir).join("bundled_grammars.rs");

    let enabled = std::env::var_os("CARGO_FEATURE_BUNDLED_GRAMMARS").is_some();
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR");
    let asset_dir = Path::new(&manifest)
        .join("assets")
        .join("grammars-prebuilt")
        .join(target);

    // Rebuild the table whenever the per-target asset directory changes.
    println!("cargo:rerun-if-changed={}", asset_dir.display());

    let mut entries = String::new();
    if enabled {
        match collect_gz(&asset_dir) {
            Ok(files) if !files.is_empty() => {
                for (name, ext, path) in files {
                    // `include_bytes!` needs a literal path; embed the
                    // absolute path so it resolves regardless of CWD.
                    entries.push_str(&format!(
                        "    ({name:?}, {ext:?}, include_bytes!({:?})),\n",
                        path
                    ));
                }
            }
            Ok(_) => {
                println!(
                    "cargo:warning=bundled-grammars enabled but no *.gz found in {} — run `vorto grammar bundle` for this target first; binary will ship with no embedded grammars",
                    asset_dir.display()
                );
            }
            Err(e) => {
                println!(
                    "cargo:warning=bundled-grammars: reading {} failed ({e}); shipping no embedded grammars",
                    asset_dir.display()
                );
            }
        }
    }

    let contents = format!(
        "// @generated by build.rs — do not edit.\n\
         /// (grammar name, dylib extension, gzip-compressed library bytes)\n\
         pub static BUNDLED_GRAMMARS: &[(&str, &str, &[u8])] = &[\n{entries}];\n"
    );
    std::fs::write(&dest, contents).expect("writing bundled_grammars.rs");
}

/// List `<name>.<ext>.gz` files in `dir`, returning `(name, ext, abs_path)`
/// sorted by name. The double extension is split so the runtime knows what
/// suffix to write the decompressed library under.
fn collect_gz(dir: &Path) -> std::io::Result<Vec<(String, String, std::path::PathBuf)>> {
    let mut out = Vec::new();
    if !dir.exists() {
        return Ok(out);
    }
    for entry in std::fs::read_dir(dir)? {
        let path = entry?.path();
        let Some(fname) = path.file_name().and_then(|s| s.to_str()) else {
            continue;
        };
        // Expect `<name>.<so|dylib|dll>.gz`.
        let Some(stem) = fname.strip_suffix(".gz") else {
            continue;
        };
        let Some((name, ext)) = stem.rsplit_once('.') else {
            continue;
        };
        if !matches!(ext, "so" | "dylib" | "dll") {
            continue;
        }
        out.push((name.to_string(), ext.to_string(), path));
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(out)
}
